// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_users_by_id.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUsersByID = `-- name: GetUsersByID :one
select id, created_at, updated_at, username, password, email from users
where id = $1
`

func (q *Queries) GetUsersByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRowContext(ctx, getUsersByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.Password,
		&i.Email,
	)
	return i, err
}
