// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Message struct {
	ID        int32         `json:"id"`
	UserID    sql.NullInt32 `json:"user_id"`
	Content   string        `json:"content"`
	Iv        string        `json:"iv"`
	Salt      string        `json:"salt"`
	CreatedAt sql.NullTime  `json:"created_at"`
}

type User struct {
	ID           int32        `json:"id"`
	Email        string       `json:"email"`
	Username     string       `json:"username"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
}
